export interface UsStates {
  Code: string;
  State: string;
}

// prettier-ignore
export const usStates: UsStates[] = [
  { Code: 'AL', State: 'Alabama' },
  { Code: 'AK', State: 'Alaska' },
  { Code: 'AZ', State: 'Arizona' },
  { Code: 'AR', State: 'Arkansas' },
  { Code: 'CA', State: 'California' },
  { Code: 'CO', State: 'Colorado' },
  { Code: 'CT', State: 'Connecticut' },
  { Code: 'DE', State: 'Delaware' },
  { Code: 'DC', State: 'District of Columbia' },
  { Code: 'FL', State: 'Florida' },
  { Code: 'GA', State: 'Georgia' },
  { Code: 'HI', State: 'Hawaii' },
  { Code: 'ID', State: 'Idaho' },
  { Code: 'IL', State: 'Illinois' },
  { Code: 'IN', State: 'Indiana' },
  { Code: 'IA', State: 'Iowa' },
  { Code: 'KS', State: 'Kansas' },
  { Code: 'KY', State: 'Kentucky' },
  { Code: 'LA', State: 'Louisiana' },
  { Code: 'ME', State: 'Maine' },
  { Code: 'MD', State: 'Maryland' },
  { Code: 'MA', State: 'Massachusetts' },
  { Code: 'MI', State: 'Michigan' },
  { Code: 'MN', State: 'Minnesota' },
  { Code: 'MS', State: 'Mississippi' },
  { Code: 'MO', State: 'Missouri' },
  { Code: 'MT', State: 'Montana' },
  { Code: 'NE', State: 'Nebraska' },
  { Code: 'NV', State: 'Nevada' },
  { Code: 'NH', State: 'New Hampshire' },
  { Code: 'NJ', State: 'New Jersey' },
  { Code: 'NM', State: 'New Mexico' },
  { Code: 'NY', State: 'New York' },
  { Code: 'NC', State: 'North Carolina' },
  { Code: 'ND', State: 'North Dakota' },
  { Code: 'OH', State: 'Ohio' },
  { Code: 'OK', State: 'Oklahoma' },
  { Code: 'OR', State: 'Oregon' },
  { Code: 'PA', State: 'Pennsylvania' },
  { Code: 'RI', State: 'Rhode Island' },
  { Code: 'SC', State: 'South Carolina' },
  { Code: 'SD', State: 'South Dakota' },
  { Code: 'TN', State: 'Tennessee' },
  { Code: 'TX', State: 'Texas' },
  { Code: 'UT', State: 'Utah' },
  { Code: 'VT', State: 'Vermont' },
  { Code: 'VA', State: 'Virginia' },
  { Code: 'WA', State: 'Washington' },
  { Code: 'WV', State: 'West Virginia' },
  { Code: 'WI', State: 'Wisconsin' },
  { Code: 'WY', State: 'Wyoming' }
];
