import { Injectable, computed, signal } from '@angular/core';

export interface Person extends d3.SimulationNodeDatum {
  displayName: string;
  index: number;
  color: string;
}

export type Relationship = d3.SimulationLinkDatum<Person>;

export interface RelMap {
  people: Person[];
  relationships: Relationship[];
}

const names = [
  'Celestine Reilly',
  'Missouri McLaughlin',
  'Mrs. Frida King',
  'Colten Waelchi DDS',
  'Kayleigh Schimmel',
  'Krystel Marquardt',
  'Aida Stamm',
  'Jude Anderson',
  'Ron VonRueden',
  "Nora O'Conner",
  'Kaley Dickinson',
  'Olen Ruecker',
  'Gino Romaguera',
  'Leanna Will',
  'Kristofer Hane',
  'Janie Bahringer',
  'Herbert Rohan',
  'Geo Rice',
  'Reba Baumbach',
  'Virgil Boyle',
  'Mr. Rebeka Huel',
  'Alexie Bartoletti',
  'Carlotta Mueller',
  'Soledad Mosciski',
  'Jerod Weimann',
  'Emory Legros',
  'Darby Bednar DVM',
  'Tatyana DuBuque II',
  'Mr. Minerva Donnelly',
  'Monserrate Schaefer',
  'Dagmar Schaefer',
  'Lottie Rohan III',
  'Ernestina Medhurst DVM',
  'Claudie Fritsch',
  'Lukas Bednar',
  'Pierre McClure',
  'Caden Hammes',
  'Maurice Robel',
  'Lacey Bauch',
  'Blanche Lesch',
  'Ebony Mante',
  'Buford Jakubowski',
  'Ayla Leffler IV',
  'Dr. Sophia Durgan',
  'Pearl Kohler',
  'Ms. Hobart Hauck',
  'Tatum Roob',
  'Justyn Buckridge',
  'Ms. Efren Fisher',
  'Helen Ferry Sr.',
  'Adolf Leffler',
  'Yessenia Bayer IV',
  'Kameron Harris',
  'Maiya Gleason',
  'Ricky Block',
  'Vernon Bartell',
  'Dr. Garret Kirlin',
  'Marlon Williamson',
  'Gladys McGlynn',
  'Miss Juston Deckow',
  'Demetris Nicolas',
  'Conrad Bradtke',
  'Rogers Klocko',
  'Kristian Miller',
  'Shyanne Halvorson',
  'Anabel Kohler',
  'Jazmyne Schowalter',
  'Elvis Toy',
  'Lyda Steuber',
  'Arnoldo Berge',
  'Wilber Langosh',
  'Miguel Abshire V',
  'Elza Kreiger',
  'Myah Hilll PhD',
  'Ms. Magnolia Hand',
  'Allie Hyatt',
  'Antonina White DVM',
  'Jolie Lebsack I',
  'Zelma Orn',
  'Candido Muller',
  'Fred Ratke',
  'Hayley Emard',
  'Lauriane Langworth',
  'Ryann Brekke',
  'Ryley Cruickshank IV',
  'Kirstin Ortiz',
  'Payton Watsica',
  'Daisy Collins',
  'Arvel Haag Sr.',
  'Ward Tromp',
  'Macie Bosco',
  'Justice Dicki',
  'Jaren Kirlin',
  'Josefina Feeney',
  'Norma Renner',
  'Ida Kuhlman',
  'Winona Funk',
  'Isom Jerde',
  'Cheyanne Huels',
  'Beulah Sporer',
  'Bernadette Miller',
  'Dr. Sophia Kuphal',
  'Loraine Considine',
  'Estrella VonRueden',
  'Dr. Sophie Mosciski',
  'Kitty Ledner',
  'Kitty Huel',
  'Mellie Stamm',
  'Andreanne Koch',
  'Ally Ankunding',
  'Gladys Kshlerin',
  'Eliseo Bernhard',
  'Rahul Lebsack',
  'Dallas Orn',
  'Ms. Nelle Hudson',
  'Sonya Corwin',
  'Mr. Adam Hickle',
  'Van Metz',
  'Vilma Funk',
  'Delia Streich',
  'Liza Kautzer',
  'Gregoria Leannon',
  'Jackeline Zemlak',
  'Janet Dickens',
  'Rocio Kuvalis',
  'Dewitt Trantow',
  'Ms. Roscoe Ryan',
  'Lloyd Breitenberg',
  'Trinity Rosenbaum',
  'Pierce Haag',
  'Cassandra Simonis',
  'Heber King',
  'Karine Emmerich',
  'Guillermo Macejkovic',
  'Carlo Barrows',
  'Marion Jerde',
  'Dina Champlin I',
  'Robyn Cruickshank Sr.',
  'Esperanza Kuhlman',
  'Liam Will',
  'Freeman Auer',
  'Stanley Denesik',
  'Elwyn White',
  'Destin Schumm',
  'Miss Mortimer Lehner',
  'Timothy Grimes',
  'Montana Lynch',
  'Caterina Lehner PhD',
  'Athena Lang V',
  'Corine Romaguera',
  'Magdalen Schinner',
  'Chelsie Homenick',
  'Mrs. Leonardo Hickle',
  'Margaret Trantow',
  'Emmett Dickinson',
  'Dora Schmeler IV',
  'Raleigh Kuphal',
  'Kevin Wolff',
  'Godfrey Ryan',
  'Miguel Daugherty',
  'Syble Muller',
  'Aisha Thiel',
  'Adonis Hayes',
  'Nathaniel Lubowitz',
  'Daija Goyette',
  'Dr. Elinore Sauer',
  'Alberta Torphy',
  'Crystel Wilderman',
  'Sofia Lubowitz IV',
  'Keeley Bosco DDS',
  'Alyson Jaskolski',
  'Erika Bernhard',
  'Filomena Greenholt',
  'Halie Trantow',
  'Frederick Ziemann',
  'Rashawn Hills Jr.',
  'Josh Cruickshank',
  'Filiberto Mohr',
  'Kyla Dietrich',
  'Dolores Daniel',
  'Gladys Rice',
  'Aurore Adams II',
  'Raymond Vandervort',
  'Monserrate Kuvalis',
  'Emiliano Dickens',
  'Kaci Abbott',
  'Miss Erna Mills',
  'Dillan Koch',
  'Ms. Estevan Huels',
  'Maida Lebsack',
  'Tatyana Rath',
  'Juvenal Koss',
  'Judy Schinner',
  'Seth Legros',
  'Emely Stokes',
  'Dewitt Greenholt',
  'Ora Green',
  'Mrs. Francis Stanton',
  'Rachel Murazik',
  'Alize Rippin',
  'Aurelio Abshire',
  'Claudia Mertz Sr.',
  'Vernie Bartoletti',
  'Lula Smith',
  'Mrs. Layne Daugherty',
  'Thea Langworth',
  'Alessia Moen',
  'Garett Mante',
  'Guillermo Buckridge',
  'Danyka Schumm',
  'Cristina Schultz',
  'Gerald Gerlach',
  'Winston Terry',
  'Dr. Clemens Huels',
  'Jacinthe Kub',
  'Dr. Betty Considine',
  'Lincoln Kreiger',
  'Ashlee Hickle',
  'Jermain Nader DDS',
  'Eladio Kozey',
  'Kenny Schinner',
  'Mafalda Welch',
  'Lazaro Heller',
  'Tevin Kautzer',
  'Davon Gorczany',
  'Florencio Balistreri III',
  'Sydni Hodkiewicz',
  'Destin Thiel',
  'Marcia McClure',
  'Art Williamson Sr.',
  'Dee Nitzsche',
  'Frederik Nader',
  'Vivianne Kub',
  'Ressie Schinner',
  'Desmond Howe',
  'Lucienne Gottlieb',
  'Ervin Mante',
  'Green Hilpert',
  'Dr. Tyrese Olson',
  'Johnathon Bergstrom',
  'Krista Jaskolski',
  'Therese Lind',
  'Bernita Konopelski',
  'Rosemarie Pfannerstill',
  'Dejah Eichmann',
  'Darlene Hodkiewicz DVM',
  'Mr. Dannie Hills',
  'Mr. Bessie Schmidt',
  'Shaun Towne',
  'Kiara Williamson IV'
];

const mockData: RelMap = {
  people: [],
  relationships: []
};

// Generate mock data from the list of names.
names.forEach((name, index) => {
  // Assign colors to individual nodes.
  mockData.people.push({
    displayName: name,
    index,
    color: `var(--abc-category-${(index % 8) + 1}-color)`
  });

  // Connect this node to some other random node.
  mockData.relationships.push({
    source: name,
    target: names[Math.floor(Math.random() * names.length)]
  });
});

@Injectable({
  providedIn: 'root'
})
export class GraphService {
  // Pretend we're loading data from an external source.
  private readonly peopleAndRelationships = signal(mockData);

  readonly people = computed(
    () => this.peopleAndRelationships().people
  );

  readonly relationships = computed(
    () => this.peopleAndRelationships().relationships
  );
}
